const POST = {
  FETCH_DATA: "FETCH_DATA",
  LOAD_POST_SUCCESS: "LOAD_POST_SUCCESS",
  LOAD_GET: "LOAD_GET",
  REMOVE_POSTS: "REMOVE_POSTS",
  ADD_POST: "ADD_POST",
  ADD_POST_SUCCESS: "ADD_POST_SUCCESS"
};
const MESSAGES = {
  SUCCESS: "{value} SUCCESS",
  Error: "{value} Error"
};
export { POST, MESSAGES };
